### ISSUE TITLE
What is `base_image`?

### ISSUE THREAD

**Issue by geekman2** [ntaylorwss/kerasgym#5]
https://github.com/ntaylorwss/kerasgym/blob/16f11ac3c6bf3636955166d93253f8eaab0aa886/docker/Dockerfile#L1

I'm reasonably certain this isn't https://github.com/phusion/baseimage-docker. Which leads me to believe that it is in fact a locally built image that you're assuming exists, since I can't find another dockerfile in this repo.

**Comment by ntaylorwss** [comment]
Also resolved by fixing #1.
