### ISSUE TITLE
What is the point of this logic?

### ISSUE THREAD

**Issue by geekman2** [ntaylorwss/kerasgym#6]
https://github.com/ntaylorwss/kerasgym/blob/16f11ac3c6bf3636955166d93253f8eaab0aa886/docker/start#L14-L33

You are checking if a GPU image exists, and if it does, starting it. But what if someone builds the GPU image, but doesn't have a GPU? This should be a parameter.

Also, you parameterise $port, but then hardcode it, so what's the point?

**Comment by ntaylorwss** [comment]
The port is starting at 8888, then being decremented. It's not a hardcoding; line 31 decrements.
docker/build asks if you have a GPU, and builds that image if you say yes. If you say yes to having a GPU and you don't have a GPU, you're dumb and I don't want to deal with you~.

**Comment by geekman2** [comment]
To the GPU point, fine. But the decrementing logic should be commented to explain that it's going on and more importantly why
