### ISSUE TITLE
One argument per line

### ISSUE THREAD

**Issue by geekman2** [ntaylorwss/kerasgym#9]
https://github.com/ntaylorwss/kerasgym/blob/16f11ac3c6bf3636955166d93253f8eaab0aa886/kerasgym/agents/agents.py#L15-L17

Yes, I know it's kind of gross looking, but this is worse. It's hard to read, and especially hard to see all the args

**Comment by ntaylorwss** [comment]
If I move down repeated_actions, which I thought I had done, the top line is all object arguments, the middle line is all int arguments, and the last line is all keyword arguments. Plus you know how I feel about vertical space

**Comment by geekman2** [comment]
You have an ultrawide vertical monitor, and you're also concerned about horizontal space, so don't give me that nonsense. That said, if there's a method to the madness then HOOO BOOOY, IT'S TIME FOR COMMENTS

**Comment by ntaylorwss** [comment]
Does the documentation help?

**Comment by geekman2** [comment]
Yeah, it's better
